// <auto-generated />
using System;
using BVS.Models.Entity.ContextBVS;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BVS.Migrations
{
    [DbContext(typeof(BVSContext))]
    partial class BVSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BVS.Models.Entity.CompradorAssociado.Associado", b =>
                {
                    b.Property<Guid>("CadastroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("DataDaParceria")
                        .HasColumnType("date");

                    b.Property<string>("Fazenda")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<Guid?>("IdComprador")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("CadastroId");

                    b.HasIndex("IdComprador");

                    b.ToTable("Associados");
                });

            modelBuilder.Entity("BVS.Models.Entity.CompradorAssociado.Comprador", b =>
                {
                    b.Property<Guid>("CadastroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("CadastroId");

                    b.ToTable("Compradores", (string)null);
                });

            modelBuilder.Entity("BVS.Models.Entity.Parceria.AlteracaoSaida", b =>
                {
                    b.Property<Guid>("BoiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Arroba")
                        .HasColumnType("numeric(7,2)");

                    b.Property<string>("Classificacao")
                        .HasColumnType("text");

                    b.Property<string>("CompraVenda")
                        .HasColumnType("text");

                    b.Property<Guid>("IdAssociado")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdComprador")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InicioParceriaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PesoBruto")
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal?>("PesoMedioAlterado")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("RendimentoCarcaca")
                        .HasColumnType("numeric(7,2)");

                    b.Property<DateTime>("Saida")
                        .HasColumnType("date");

                    b.HasKey("BoiId");

                    b.HasIndex("IdAssociado");

                    b.HasIndex("IdComprador");

                    b.HasIndex("InicioParceriaId");

                    b.ToTable("AlteracaoSaidas");
                });

            modelBuilder.Entity("BVS.Models.Entity.Parceria.InicioParceria", b =>
                {
                    b.Property<Guid>("BoiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Arroba")
                        .HasColumnType("numeric(7,2)");

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompraVenda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataInicioParceria")
                        .HasColumnType("date");

                    b.Property<Guid>("IdAssociado")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdComprador")
                        .HasColumnType("uuid");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PesoBruto")
                        .HasColumnType("numeric(7,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("RendimentoCarcaca")
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("BoiId");

                    b.HasIndex("IdAssociado");

                    b.HasIndex("IdComprador");

                    b.ToTable("InicioParcerias");
                });

            modelBuilder.Entity("BVS.Models.Entity.CompradorAssociado.Associado", b =>
                {
                    b.HasOne("BVS.Models.Entity.CompradorAssociado.Comprador", "Comprador")
                        .WithMany("Associados")
                        .HasForeignKey("IdComprador")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Comprador");
                });

            modelBuilder.Entity("BVS.Models.Entity.Parceria.AlteracaoSaida", b =>
                {
                    b.HasOne("BVS.Models.Entity.CompradorAssociado.Associado", "Associado")
                        .WithMany("AlteracaoSaidas")
                        .HasForeignKey("IdAssociado")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("BVS.Models.Entity.CompradorAssociado.Comprador", "Comprador")
                        .WithMany("AlteracaoSaidas")
                        .HasForeignKey("IdComprador")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("BVS.Models.Entity.Parceria.InicioParceria", "InicioParceria")
                        .WithMany("AlteracaoSaidas")
                        .HasForeignKey("InicioParceriaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Associado");

                    b.Navigation("Comprador");

                    b.Navigation("InicioParceria");
                });

            modelBuilder.Entity("BVS.Models.Entity.Parceria.InicioParceria", b =>
                {
                    b.HasOne("BVS.Models.Entity.CompradorAssociado.Associado", "Associado")
                        .WithMany("InicioParcerias")
                        .HasForeignKey("IdAssociado")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BVS.Models.Entity.CompradorAssociado.Comprador", "Comprador")
                        .WithMany("InicioParcerias")
                        .HasForeignKey("IdComprador")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Associado");

                    b.Navigation("Comprador");
                });

            modelBuilder.Entity("BVS.Models.Entity.CompradorAssociado.Associado", b =>
                {
                    b.Navigation("AlteracaoSaidas");

                    b.Navigation("InicioParcerias");
                });

            modelBuilder.Entity("BVS.Models.Entity.CompradorAssociado.Comprador", b =>
                {
                    b.Navigation("AlteracaoSaidas");

                    b.Navigation("Associados");

                    b.Navigation("InicioParcerias");
                });

            modelBuilder.Entity("BVS.Models.Entity.Parceria.InicioParceria", b =>
                {
                    b.Navigation("AlteracaoSaidas");
                });
#pragma warning restore 612, 618
        }
    }
}
